### ISSUE TITLE
Refactor Parse

### ISSUE THREAD

**Issue by codelegend** [TalkTakesTime/Pokemon-Showdown-Bot#46]
[enhancement] Instead of passing the connection over to `Parse#message`, `Parse#say` and to commands, why not store the connection in `Parse`, (say like `Parse.activeConnection = connection` when the websocket `connect` event is fired.)
This could simplify the Parse layer, and the commands API.

Are there any potential bugs/errors that can arise?
- One thing I thought of is if multiple connections get opened at the same time. but this never happened.

**Comment by codelegend** [comment]
@Morfent

**Comment by Morfent** [comment]
The only situation I can think of where there this would be an issue is if I were to decide to add support for connecting to multiple servers in the future, which I don't plan on doing. As far as I know, ``global.send`` would be the only function that would ever use the connection if it were cached, so it'd be better off kept in a local variable in main.js instead of in ``Parse``. I'll take a look at this later.

**Comment by codelegend** [comment]
yeah, keeping it local to main.js would also work equally well
